db-queries:
  unit:
    select: SELECT * FROM unit
    insert: INSERT INTO unit(unit_code, unit_name, is_fractional, fractional_digits) VALUES (?, ?, ?, ?)
    delete: DELETE FROM unit
  address:
    select: SELECT * FROM address
    insert: INSERT INTO address (addr_line_1, addr_line_2, city, state, country, pincode) VALUES (?, ?, ?, ?, ?, ?)
    delete: DELETE FROM address
  company:
    select: SELECT * FROM company
    insert: INSERT INTO company (company_name, headquarter_addr_id, gstin) VALUES (?, ?, ?)
    delete: DELETE FROM company
  branchLocation:
    select: SELECT * FROM branch_location
    insert: INSERT INTO branch_location (bl_name, company_id, bl_addr_id) VALUES (?, ?, ?)
    delete: DELETE FROM branch_location
  item:
    select: SELECT * FROM item
    insert: INSERT INTO item (item_name, batch_number, unit_code, purchase_price, selling_price, opening_balance_date, opening_balance_qty, expiry_date) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
    delete: DELETE FROM item