db-queries:
  unit:
    select: SELECT * FROM unit
    insert: INSERT INTO unit(unit_code, unit_name, is_fractional, fractional_digits) VALUES (?, ?, ?, ?)
    delete: DELETE FROM unit
  address:
    select: SELECT * FROM address
    insert: INSERT INTO address (addr_line_1, addr_line_2, city, state, country, pincode) VALUES (?, ?, ?, ?, ?, ?)
    delete: DELETE FROM address
  company:
    select: SELECT * FROM company
    insert: INSERT INTO company (company_name, headquarter_addr_id, gstin) VALUES (?, ?, ?)
    delete: DELETE FROM company